using System.Text;

namespace LautzOfCode.EnumGenerator;

public static class SourceGenerationHelper {
  const string Header = @"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the NetEscapades.EnumGenerators source generator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable";

  public const string Attribute = Header + @"

namespace LautzOfCode.EnumGenerators
{
    /// <summary>
    /// Add to enums to indicate that extension methods should be generated for the type
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Enum)]
    public class EnumExtensionsAttribute : System.Attribute
    {
    }
}
";

  public static string GenerateExtensionClass(StringBuilder sb, EnumToGenerate enumToGenerate) {
    sb.Append(Header);

    if (!string.IsNullOrEmpty(enumToGenerate.Namespace)) {
      sb.Append(@"
namespace ").Append(enumToGenerate.Namespace).Append(@"
{");
    }

    sb.Append(@"
    ").Append(enumToGenerate.IsPublic ? "public" : "internal").Append(@" static partial class ")
      .Append(enumToGenerate.Name).Append(@"
    {
        public static string ToStringFast(this ").Append(enumToGenerate.FullyQualifiedName).Append(@" value)
            => value switch
            {");
    foreach (string key in enumToGenerate.Values.Select(m => m.Key)) {
      sb.Append(@"
                ").Append(enumToGenerate.FullyQualifiedName).Append('.').Append(key)
        .Append(" => nameof(")
        .Append(enumToGenerate.FullyQualifiedName).Append('.').Append(key).Append("),");
    }

    sb.Append(@"
                _ => value.ToString(),
            };");

    if (enumToGenerate.HasFlags) {
      sb.Append(@"

        public static bool HasFlag(this ").Append(enumToGenerate.FullyQualifiedName).Append(@" value, ")
        .Append(enumToGenerate.FullyQualifiedName).Append(@" flag)
            => value switch
            {
                0  => flag.Equals(0),
                _ => (value & flag) != 0,
            };");
    }

    sb.Append(@"

       public static bool IsDefined(").Append(enumToGenerate.FullyQualifiedName).Append(@" value)
            => value switch
            {");
    foreach (KeyValuePair<string, object> member in enumToGenerate.Values) {
      sb.Append(@"
                ").Append(enumToGenerate.FullyQualifiedName).Append('.').Append(member.Key)
        .Append(" => true,");
    }

    sb.Append(@"
                _ => false,
            };

        public static bool IsDefined(string name)
            => name switch
            {");
    foreach (KeyValuePair<string, object> member in enumToGenerate.Values) {
      sb.Append(@"
                nameof(").Append(enumToGenerate.FullyQualifiedName).Append('.').Append(member.Key)
        .Append(@") => true,");
    }

    sb.Append(@"
                _ => false,
            };

        public static bool TryParse(
#if NETCOREAPP3_0_OR_GREATER
            [System.Diagnostics.CodeAnalysis.NotNullWhen(true)]
#endif
            string? name, 
            bool ignoreCase, 
            out ").Append(enumToGenerate.FullyQualifiedName).Append(@" value)
            => ignoreCase ? TryParseIgnoreCase(name, out value) : TryParse(name, out value);

        private static bool TryParseIgnoreCase(
#if NETCOREAPP3_0_OR_GREATER
            [System.Diagnostics.CodeAnalysis.NotNullWhen(true)]
#endif
            string? name, 
            out ").Append(enumToGenerate.FullyQualifiedName).Append(@" value)
        {
            switch (name)
            {");
    foreach (string key in enumToGenerate.Values.Select(m=>m.Key)) {
      sb.Append(@"
                case { } s when s.Equals(nameof(").Append(enumToGenerate.FullyQualifiedName).Append('.')
        .Append(key).Append(@"), System.StringComparison.OrdinalIgnoreCase):
                    value = ").Append(enumToGenerate.FullyQualifiedName).Append('.').Append(key).Append(@";
                    return true;");
    }

    sb.Append(@"
                case { } s when ").Append(enumToGenerate.UnderlyingType).Append(@".TryParse(name, out var val):
                    value = (").Append(enumToGenerate.FullyQualifiedName).Append(@")val;
                    return true;
                default:
                    value = default;
                    return false;
            }
        }

        public static bool TryParse(
#if NETCOREAPP3_0_OR_GREATER
            [System.Diagnostics.CodeAnalysis.NotNullWhen(true)]
#endif
            string? name, 
            out ").Append(enumToGenerate.FullyQualifiedName).Append(@" value)
        {
            switch (name)
            {");
    foreach (string key in enumToGenerate.Values.Select(m => m.Key)) {
      sb.Append(@"
                case nameof(").Append(enumToGenerate.FullyQualifiedName).Append('.').Append(key).Append(@"):
                    value = ").Append(enumToGenerate.FullyQualifiedName).Append('.').Append(key).Append(@";
                    return true;");
    }

    sb.Append(@"
                case { } s when ").Append(enumToGenerate.UnderlyingType).Append(@".TryParse(name, out var val):
                    value = (").Append(enumToGenerate.FullyQualifiedName).Append(@")val;
                    return true;
                default:
                    value = default;
                    return false;
            }
        }

        public static ").Append(enumToGenerate.FullyQualifiedName).Append(@"[] GetValues()
        {
            return new[]
            {");
    foreach (string key in enumToGenerate.Values.Select(m=>m.Key)) {
      sb.Append(@"
                ").Append(enumToGenerate.FullyQualifiedName).Append('.').Append(key).Append(',');
    }

    sb.Append(@"
            };
        }

        public static string[] GetNames()
        {
            return new[]
            {");
    foreach (string key in enumToGenerate.Values.Select(m=>m.Key)) {
      sb.Append(@"
                nameof(").Append(enumToGenerate.FullyQualifiedName).Append('.').Append(key).Append("),");
    }

    sb.Append(@"
            };
        }
    }");
    if (!string.IsNullOrEmpty(enumToGenerate.Namespace)) {
      sb.Append(@"
}");
    }

    return sb.ToString();
  }
}
